spring.application.name=backend

spring.datasource.url=jdbc:oracle:thin:@//TU_HOST:1521/TU_SERVICE_NAME
spring.datasource.username=TU_USER
spring.datasource.password=TU_PASSWORD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
